[package]
name = "loader-binary"
version = "0.0.0"

#[bin]
#path = "src/main.rs"

[dependencies]
byteorder = { path = "../../libbyteorder" }
macros = { path = "../../libmacros" }
cmdline_words_parser = { path = "../../../externals/crates.io/cmdline_words_parser" }

# Part of sysroot
#syscalls = { path = "../../libsyscalls" }
#loader = { path = "../lib" }
