[package]
name = "loader-binary"
version = "0.0.0"

[lib]
path = "src/main.rs"

[dependencies]
loader = { path = "../lib" }
syscalls = { path = "../../libsyscalls" }
byteorder = { path = "../../libbyteorder" }
macros = { path = "../../libmacros" }
cmdline_words_parser = { path = "../../../externals/crates.io/cmdline_words_parser" }
